name: "Linting"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1.4.4
      
    - name: eslint
      run: |
        npm i eslint -g
        eslint js/script.js
    - name: css-lint
      run: |
        npm i csslint -g
        csslint css/style.css
